![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


In [5]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


In [10]:
np.where(my_array % 2 == 1, True, False)

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [11]:
print(my_array[np.where(my_array % 2 == 1, True, False )][::-1])

[9 7 5 3 1]


In [13]:
np.flip(my_array[my_array % 2 == 1])

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [14]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
print(my_array[-2:-4:-1])

[8 7]


In [16]:
print(np.flip(my_array[(my_array > 6) & (my_array < 9)]))

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [17]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [28]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print(my_matrix.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [23]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [24]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [25]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


In [41]:
np.hsplit(my_matrix, [2])

[array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]),
 array([[ 3,  4,  5],
        [ 8,  9, 10],
        [13, 14, 15],
        [18, 19, 20]])]

In [40]:
np.vsplit(np.hsplit(my_matrix, [2])[0], [2])[0]

array([[1, 2],
       [6, 7]])

In [29]:
my_matrix_sl = my_matrix[:2,:2].copy()
my_matrix_sl[0,0] = 0
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [61]:
# print(my_matrix)
# mask = ([True,True,False,False],[True,True,False,False, False])
# my_matrix[mask]

In [59]:
# my_matrix[[True,True,False,False]]

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [63]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [66]:
print(my_matrix[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [67]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [70]:
print(my_matrix[:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [73]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [74]:
x == "Loro"

array([ True, False, False,  True, False])

In [76]:
print(x[x == "Loro"])

['Loro' 'Loro']


In [85]:
np.where(x == "Loro")

(array([0, 3], dtype=int64),)

In [86]:
x[np.where(x == "Loro")[0]]

array(['Loro', 'Loro'], dtype='<U5')

In [90]:
np.extract(x == "Loro", x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [91]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [94]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [97]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [100]:
print(x.itemsize)
print(x.nbytes)
print(x.dtype)

8
80
float64


In [103]:
x = np.full(10, 0)
print(x)
print(x.itemsize)
print(x.nbytes)
print(x.dtype)

[0 0 0 0 0 0 0 0 0 0]
4
40
int32


In [131]:
x = np.full(10, 0, dtype=np.int8)
print(x)
print(x.itemsize)
print(x.nbytes)
print(x.dtype)

[0 0 0 0 0 0 0 0 0 0]
1
10
int8


In [132]:
2 ** 8 #[-128,127]

256

In [134]:
# print(x)
x[0] = 128
print(x)

[-128    0    0    0    0    0    0    0    0    0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [135]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [136]:
np.flip(x)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [137]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [141]:
ejer_12 = np.array([1,2,0,0,4,0])

np.where(ejer_12 != 0)[0]

array([0, 1, 4], dtype=int64)

In [142]:
ejer_12[np.where(ejer_12 != 0)[0]]

array([1, 2, 4])

In [145]:
def f_ejer_12(vector):
    return np.where(vector != 0)[0]

In [149]:
f_ejer_12(np.array([4,7,2,0,0,5,0]))

array([0, 1, 2, 5], dtype=int64)

In [151]:
np.nonzero(ejer_12)[0]

array([0, 1, 4], dtype=int64)

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [172]:
x = np.random.randint(100, size=(10,10))
print(x)

[[75 48 75  1 66  1 79  4 27 90]
 [31 25 25 30 58  5  8 85  0 94]
 [ 7 77 42 60 47 24  6 77  5 33]
 [73 48 39 20 10 86 37 58 73 51]
 [62 62 49 33  0 89 74 58 47 44]
 [86 21 75 28 84 33 97 50 87 96]
 [12 80 71 20 85 66 50 98 75 37]
 [82  2 89 50 86 13 67 43 58 96]
 [14 43 40 48 15  0 57 96 91  8]
 [16 89 20 13 47 47 58 98 45 64]]


In [180]:
print("Mínimo", np.min(x), x.min())
print("Máximo", np.max(x), x.max())
print("Sumatorio", np.sum(x), x.sum())
print("Media", np.mean(x), x.mean())
print("Mediana", np.median(x))

Mínimo 0 0
Máximo 98 98
Sumatorio 4964 4964
Media 49.64 49.64
Mediana 48.5


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [225]:
np.random.seed(346)
x = np.random.random(30)
print(x)
print(x.mean())

[0.59361953 0.00910225 0.18560981 0.44345619 0.9507039  0.66820884
 0.01833834 0.63313172 0.33851554 0.4396443  0.04111529 0.95927841
 0.25268495 0.22990873 0.82844003 0.14590685 0.55688381 0.64361552
 0.20017478 0.48673937 0.86548364 0.48961823 0.45626586 0.65494751
 0.87402414 0.11379659 0.28231216 0.38937048 0.36253885 0.90331575]
0.4672250456389294


In [252]:
# np.random.seed(346)
x = np.random.random(30)
print(x)
print(x.mean())

[0.82460592 0.28133132 0.19568944 0.41380727 0.75061462 0.85470442
 0.82628305 0.16135259 0.80252802 0.19580827 0.22240603 0.71459076
 0.08901271 0.38502846 0.19742893 0.55464215 0.7883904  0.60998883
 0.66444953 0.94136876 0.57849432 0.16383305 0.75239348 0.83655796
 0.856837   0.16537632 0.22823104 0.97081082 0.66465921 0.38862533]
0.5359950005951263


In [254]:
print(x.sum()/len(x))

0.5359950005951263


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [256]:
ejer_15 = np.full((10,10), 1)
ejer_15

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [258]:
ejer_15[1:-1, 1:-1] = 0
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [259]:
ejer_15 = np.full((10,10), 0)
ejer_15

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [264]:
ejer_15[::len(ejer_15)-1,::] = 1
ejer_15[::, ::9] = 1
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [262]:
def f_ejer_15(tamaño):
    matrix = np.full(tamaño, 1)
    matrix[1:-1, 1:-1] = 0
    return matrix

In [263]:
f_ejer_15((3,3))

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [265]:
f_ejer_15((6,6))

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [267]:
x = np.full((8,8), 0)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [268]:
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [269]:
a = np.array([[1,0],
              [0,1]])

In [273]:
x = np.tile(a, (4,4))
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [275]:
x = np.random.randint(1,20, (5,5))
print(x)

[[18  4  4 19 14]
 [19 17 16 11 16]
 [ 5  6 12  4 12]
 [18 14  3  3 17]
 [ 6  3  5 19 10]]


In [276]:
np.mean(x)

11.0

In [277]:
np.std(x)

5.979966555090421

In [292]:
x_norm = (x - np.mean(x)) / np.std(x)
print(x_norm)

[[ 1.17057511 -1.17057511 -1.17057511  1.33780012  0.50167505]
 [ 1.33780012  1.00335009  0.83612508  0.          0.83612508]
 [-1.00335009 -0.83612508  0.16722502 -1.17057511  0.16722502]
 [ 1.17057511  0.50167505 -1.33780012 -1.33780012  1.00335009]
 [-0.83612508 -1.33780012 -1.00335009  1.33780012 -0.16722502]]


In [293]:
x_norm.mean()

3.3306690738754695e-18

In [294]:
x_norm.std()

1.0

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [295]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [298]:
y = x.copy()
y[(y >= 3) & (y <= 8)] = -1
print(y)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [300]:
z = x.copy()
z[(z >= 3) & (z <= 8)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [309]:
z = x.copy()
np.where((z >= 3) & (z <= 8), z * (-1), z)

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [310]:
np.where(~(z >= 3) | ~(z <= 8), z , z* (-1))

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])